import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 8080,
    host: true,
    strictPort: true,
    allowedHosts: [
      'ssh-key-generator-tunnel-umv6mse9.devinapps.com',
      'b9e5-41-80-114-9.ngrok-free.app',
      'wise-shoes-beam.loca.lt',
      'ssh-key-generator-tunnel-b5j6w7bo.devinapps.com',
      'ssh-key-generatorapp-tunnel-6li7vzrb.devinapps.com',
      'ssh-key-generator-tunnel-3wxp6sk1.devinapps.com',
      'ssh-key-generator-tunnel-uuv7fh7w.devinapps.com',
      'ssh-key-generator-tunnel-gjyylmv1.devinapps.com',
      'ssh-key-generator-tunnel-renf9v6k.devinapps.com',
      'ssh-key-generatorapp-tunnel-5kakpil6.devinapps.com',
      'ssh-key-generatorapp-tunnel-v5bq4xz4.devinapps.com',
      'ssh-key-generator-tunnel-973okc7u.devinapps.com',
      'ssh-key-generator-tunnel-uc1oyu3t.devinapps.com',
      'ssh-key-generator-tunnel-mlinf1sv.devinapps.com',
      'ssh-key-generator-tunnel-80ku8s0e.devinapps.com',
      'ssh-key-generatorapp-tunnel-9mo0kue0.devinapps.com',
      'ssh-key-generator-tunnel-bw2idapw.devinapps.com',
      'ssh-key-generator-tunnel-9arpga2g.devinapps.com',
      'ssh-key-generator-tunnel-cj2xxf8s.devinapps.com',
      'ssh-key-generator-tunnel-czzachhk.devinapps.com',
      'ssh-key-generatorapp-tunnel-fcgvuk5c.devinapps.com',
      'ssh-key-generator-tunnel-kkiunxdo.devinapps.com',
      'ssh-key-generator-tunnel-jo4ukj8z.devinapps.com',
      'ssh-key-generator-tunnel-1xnw1h0z.devinapps.com',
      'ssh-key-generatorapp-tunnel-1dcvb5jc.devinapps.com',
      'ssh-key-generator-tunnel-b0e1lz32.devinapps.com'
    ],
  },
  build: {
    outDir: 'dist',
  },
  preview: {
    port: 8080,
    host: true,
    allowedHosts: [
      'ssh-key-generator-tunnel-umv6mse9.devinapps.com',
      'b9e5-41-80-114-9.ngrok-free.app',
      'wise-shoes-beam.loca.lt',
      'ssh-key-generator-tunnel-b5j6w7bo.devinapps.com',
      'ssh-key-generatorapp-tunnel-6li7vzrb.devinapps.com',
      'ssh-key-generator-tunnel-3wxp6sk1.devinapps.com',
      'ssh-key-generator-tunnel-uuv7fh7w.devinapps.com',
      'ssh-key-generator-tunnel-gjyylmv1.devinapps.com',
      'ssh-key-generator-tunnel-renf9v6k.devinapps.com',
      'ssh-key-generatorapp-tunnel-5kakpil6.devinapps.com',
      'ssh-key-generatorapp-tunnel-v5bq4xz4.devinapps.com',
      'ssh-key-generator-tunnel-973okc7u.devinapps.com',
      'ssh-key-generator-tunnel-uc1oyu3t.devinapps.com',
      'ssh-key-generator-tunnel-mlinf1sv.devinapps.com',
      'ssh-key-generator-tunnel-80ku8s0e.devinapps.com',
      'ssh-key-generatorapp-tunnel-9mo0kue0.devinapps.com',
      'ssh-key-generator-tunnel-bw2idapw.devinapps.com',
      'ssh-key-generator-tunnel-9arpga2g.devinapps.com',
      'ssh-key-generator-tunnel-cj2xxf8s.devinapps.com',
      'ssh-key-generator-tunnel-czzachhk.devinapps.com',
      'ssh-key-generatorapp-tunnel-fcgvuk5c.devinapps.com',
      'ssh-key-generator-tunnel-kkiunxdo.devinapps.com',
      'ssh-key-generator-tunnel-jo4ukj8z.devinapps.com',
      'ssh-key-generator-tunnel-1xnw1h0z.devinapps.com',
      'ssh-key-generatorapp-tunnel-1dcvb5jc.devinapps.com',
      'ssh-key-generator-tunnel-b0e1lz32.devinapps.com'
    ],
  }
});
