import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 8080,
    host: true,
    strictPort: true,
    allowedHosts: [
      'ssh-key-generator-tunnel-umv6mse9.devinapps.com',
      'b9e5-41-80-114-9.ngrok-free.app',
      'wise-shoes-beam.loca.lt',
      'ssh-key-generator-tunnel-b5j6w7bo.devinapps.com',
      'ssh-key-generatorapp-tunnel-6li7vzrb.devinapps.com',
      'ssh-key-generator-tunnel-3wxp6sk1.devinapps.com',
      'ssh-key-generator-tunnel-uuv7fh7w.devinapps.com',
      'ssh-key-generator-tunnel-gjyylmv1.devinapps.com',
      'ssh-key-generator-tunnel-renf9v6k.devinapps.com',
      'ssh-key-generatorapp-tunnel-5kakpil6.devinapps.com',
      'ssh-key-generatorapp-tunnel-v5bq4xz4.devinapps.com',
      'ssh-key-generator-tunnel-973okc7u.devinapps.com',
      'ssh-key-generator-tunnel-uc1oyu3t.devinapps.com',
      'ssh-key-generator-tunnel-mlinf1sv.devinapps.com',
      'ssh-key-generator-tunnel-80ku8s0e.devinapps.com',
      'ssh-key-generatorapp-tunnel-9mo0kue0.devinapps.com',
      'ssh-key-generator-tunnel-bw2idapw.devinapps.com',
      'ssh-key-generator-tunnel-9arpga2g.devinapps.com',
      'ssh-key-generator-tunnel-cj2xxf8s.devinapps.com',
      'ssh-key-generator-tunnel-czzachhk.devinapps.com',
      'ssh-key-generatorapp-tunnel-fcgvuk5c.devinapps.com',
      'ssh-key-generator-tunnel-kkiunxdo.devinapps.com',
      'ssh-key-generator-tunnel-jo4ukj8z.devinapps.com',
      'ssh-key-generator-tunnel-1xnw1h0z.devinapps.com',
      'ssh-key-generatorapp-tunnel-1dcvb5jc.devinapps.com',
      'ssh-key-generator-tunnel-b0e1lz32.devinapps.com',
      'ssh-key-generator-tunnel-rvektnf7.devinapps.com',
      'ssh-key-generatorapp-tunnel-qfhvqwze.devinapps.com',
      'ssh-key-generator-tunnel-bn1o76fk.devinapps.com',
      'ssh-key-generator-tunnel-z3xmo1zq.devinapps.com',
      'ssh-key-generator-tunnel-wjehnug9.devinapps.com',
      'ssh-key-generator-tunnel-c7e42t2o.devinapps.com',
      'ssh-key-generator-tunnel-43yb5l8i.devinapps.com',
      'ssh-key-generator-tunnel-kwhzs5an.devinapps.com',
      'ssh-key-generatorapp-tunnel-fwsvj099.devinapps.com',
      'ssh-key-generator-tunnel-wci49i1s.devinapps.com',
      'ssh-key-generator-tunnel-vhj659s0.devinapps.com',
      'ssh-key-generator-tunnel-la0zas7p.devinapps.com',
      'ssh-key-generator-tunnel-qp519trn.devinapps.com',
      'ssh-key-generator-tunnel-xj5qsobw.devinapps.com',
      'ssh-key-generatorapp-tunnel-28q802vp.devinapps.com',
      'ssh-key-generator-tunnel-qsdueh5l.devinapps.com',
      'ssh-key-generator-tunnel-4efy2i38.devinapps.com',
      'ssh-key-generator-tunnel-0o98gxdd.devinapps.com',
      'ssh-key-generator-tunnel-104d2fpu.devinapps.com',
      'ssh-key-generator-tunnel-3lh84c3d.devinapps.com',
      'ssh-key-generator-tunnel-oy93ty5a.devinapps.com',
      'ssh-key-generator-tunnel-ifrtqng4.devinapps.com',
      'ssh-key-generator-tunnel-4tpev56y.devinapps.com',
      'ssh-key-generator-tunnel-171haa9l.devinapps.com',
      'ssh-key-generator-tunnel-n6uaiiw1.devinapps.com',
      'ssh-key-generator-tunnel-tm12ayhl.devinapps.com',
      'ssh-key-generator-tunnel-aedw5brm.devinapps.com',
      'ssh-key-generator-tunnel-l6l094ye.devinapps.com',
      'ssh-key-generator-tunnel-ryf4svni.devinapps.com',
      'ssh-key-generatorapp-tunnel-aw296yup.devinapps.com',
      'ssh-key-generator-tunnel-iavymyzj.devinapps.com',
      'ssh-key-generator-tunnel-vdm0mzns.devinapps.com',
      'ssh-key-generator-tunnel-mldmws7p.devinapps.com',
      'ssh-key-generator-tunnel-oqingxt9.devinapps.com',
      'ssh-key-generator-tunnel-sk0y11wt.devinapps.com',
      'ssh-key-generator-tunnel-m7pkyd00.devinapps.com',
      'ssh-key-generator-tunnel-yve56td9.devinapps.com'
    ],
  },
  build: {
    outDir: 'dist',
  },
  preview: {
    port: 8080,
    host: true,
    allowedHosts: [
      'ssh-key-generator-tunnel-umv6mse9.devinapps.com',
      'b9e5-41-80-114-9.ngrok-free.app',
      'wise-shoes-beam.loca.lt',
      'ssh-key-generator-tunnel-b5j6w7bo.devinapps.com',
      'ssh-key-generatorapp-tunnel-6li7vzrb.devinapps.com',
      'ssh-key-generator-tunnel-3wxp6sk1.devinapps.com',
      'ssh-key-generator-tunnel-uuv7fh7w.devinapps.com',
      'ssh-key-generator-tunnel-gjyylmv1.devinapps.com',
      'ssh-key-generator-tunnel-renf9v6k.devinapps.com',
      'ssh-key-generatorapp-tunnel-5kakpil6.devinapps.com',
      'ssh-key-generatorapp-tunnel-v5bq4xz4.devinapps.com',
      'ssh-key-generator-tunnel-973okc7u.devinapps.com',
      'ssh-key-generator-tunnel-uc1oyu3t.devinapps.com',
      'ssh-key-generator-tunnel-mlinf1sv.devinapps.com',
      'ssh-key-generator-tunnel-80ku8s0e.devinapps.com',
      'ssh-key-generatorapp-tunnel-9mo0kue0.devinapps.com',
      'ssh-key-generator-tunnel-bw2idapw.devinapps.com',
      'ssh-key-generator-tunnel-9arpga2g.devinapps.com',
      'ssh-key-generator-tunnel-cj2xxf8s.devinapps.com',
      'ssh-key-generator-tunnel-czzachhk.devinapps.com',
      'ssh-key-generatorapp-tunnel-fcgvuk5c.devinapps.com',
      'ssh-key-generator-tunnel-kkiunxdo.devinapps.com',
      'ssh-key-generator-tunnel-jo4ukj8z.devinapps.com',
      'ssh-key-generator-tunnel-1xnw1h0z.devinapps.com',
      'ssh-key-generatorapp-tunnel-1dcvb5jc.devinapps.com',
      'ssh-key-generator-tunnel-b0e1lz32.devinapps.com',
      'ssh-key-generator-tunnel-rvektnf7.devinapps.com',
      'ssh-key-generatorapp-tunnel-qfhvqwze.devinapps.com',
      'ssh-key-generator-tunnel-bn1o76fk.devinapps.com',
      'ssh-key-generator-tunnel-z3xmo1zq.devinapps.com',
      'ssh-key-generator-tunnel-wjehnug9.devinapps.com',
      'ssh-key-generator-tunnel-c7e42t2o.devinapps.com',
      'ssh-key-generator-tunnel-43yb5l8i.devinapps.com',
      'ssh-key-generator-tunnel-kwhzs5an.devinapps.com',
      'ssh-key-generatorapp-tunnel-fwsvj099.devinapps.com',
      'ssh-key-generator-tunnel-wci49i1s.devinapps.com',
      'ssh-key-generator-tunnel-vhj659s0.devinapps.com',
      'ssh-key-generator-tunnel-la0zas7p.devinapps.com',
      'ssh-key-generator-tunnel-qp519trn.devinapps.com',
      'ssh-key-generator-tunnel-xj5qsobw.devinapps.com',
      'ssh-key-generatorapp-tunnel-28q802vp.devinapps.com',
      'ssh-key-generator-tunnel-qsdueh5l.devinapps.com',
      'ssh-key-generator-tunnel-re436qxu.devinapps.com',
      'ssh-key-generator-tunnel-4efy2i38.devinapps.com',
      'ssh-key-generator-tunnel-0o98gxdd.devinapps.com',
      'ssh-key-generator-tunnel-104d2fpu.devinapps.com',
      'ssh-key-generator-tunnel-3lh84c3d.devinapps.com',
      'ssh-key-generator-tunnel-oy93ty5a.devinapps.com',
      'ssh-key-generator-tunnel-ifrtqng4.devinapps.com',
      'ssh-key-generator-tunnel-4tpev56y.devinapps.com',
      'ssh-key-generator-tunnel-171haa9l.devinapps.com',
      'ssh-key-generator-tunnel-n6uaiiw1.devinapps.com',
      'ssh-key-generator-tunnel-tm12ayhl.devinapps.com',
      'ssh-key-generator-tunnel-aedw5brm.devinapps.com',
      'ssh-key-generator-tunnel-l6l094ye.devinapps.com',
      'ssh-key-generator-tunnel-ryf4svni.devinapps.com',
      'ssh-key-generatorapp-tunnel-aw296yup.devinapps.com',
      'ssh-key-generator-tunnel-iavymyzj.devinapps.com',
      'ssh-key-generator-tunnel-vdm0mzns.devinapps.com',
      'ssh-key-generator-tunnel-mldmws7p.devinapps.com',
      'ssh-key-generator-tunnel-oqingxt9.devinapps.com',
      'ssh-key-generator-tunnel-sk0y11wt.devinapps.com',
      'ssh-key-generator-tunnel-m7pkyd00.devinapps.com',
      'ssh-key-generator-tunnel-yve56td9.devinapps.com'
    ],
  }
});
